### ISSUE TITLE
Support for printing without newlines

### ISSUE THREAD

**Issue by t3hmrman** [nicolaiunrein/cargo-get#14]
Hi thanks for the useful binary, `cargo-get` is very helpful for pulling information out of manifests for automation.

I find that when using `cargo-get` in scripts, I really want to be able to print versions (e.x. `package.version`) *without* newlines. Currently `cargo-get` always adds a newline which I have to then attempt to strip with other tools.

Would you be open to a contribution (I'm happy to make it) that adds a `--no-newline` option that performs a `print` instead of `println` ?

**Comment by nicolaiunrein** [comment]
Hey! I am glad to hear that you like it. I think this is a great idea. A PR would be very appreciated!

**Comment by nicolaiunrein** [comment]
Maybe instead of adding a `--no-newline` argument we could add something like a `--teminate` argument which defaults to newline   but accepts an arbitrary string value so one use CR, `\0` etc. as well

**Comment by t3hmrman** [comment]
Yeah that sounds pretty reasonable! that way people can change their terminator to whatever want, and the code change should also be pretty consistent!
