### ISSUE TITLE
cargo-get does not deal with edition 2021

### ISSUE THREAD

**Issue by XopheD** [nicolaiunrein/cargo-get#2]
Hello

cargo-get is troubleshooted when using edition 2021 in the manifest file (nightly now but will be stable at the end of the month).

```
CRATE_VERSION=`cargo get version`
105Error: Parse(Error { inner: ErrorInner { kind: Custom, line: Some(77), col: 0, at: Some(4098), message: "unknown variant `2021`, expected `2015` or `2018`", key: ["package", "edition"] } }) 
```

Best regards,

**Comment by nicolaiunrein** [comment]
Hi,
thanks for the Issue. Fixed it in 6b3506b and released as v0.3.3
Cheers,
Nico
