### ISSUE TITLE
Get version does not work for workspace packages

### ISSUE THREAD

**Issue by rguarnotta** [nicolaiunrein/cargo-get#3]
@nicolaiunrein would it be possible to add a feature that returns version of a `workspace.package` on top of regular `package`? 

```
[workspace.package]
version = "1.7.37"
authors = ["someone"]
description = "Some tool."
```

**Comment by nicolaiunrein** [comment]
I wasn't aware of the syntax I only know this syntax:

```
[workspace]
members = ["hello_world"]
```

can you point me to a repo that used this syntax or to the docs?

If you know the path to the workspace package you could already use the `--root` flag.

**Comment by rguarnotta** [comment]
I think that's a new addition from the Rust 1.64 update. It handles fields inheritance, including version, for members of that workspace. Here are the details: 

https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html
https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table

It'd be great to have `cargo get version`work when we point to the workspace cargo file as well as pointing to the packages cargo files. 

### Code structure

I cannot point you to the repo that use the syntax but here is the structure: 
```
.
├── Cargo.toml
├── CHANGELOG.md
├── first_service
│  ├── Cargo.toml
│  ├── src
│  │  └── main.rs
├── second_service
│  ├── Cargo.toml
│  ├── README.md
│  └── src
│     └── main.rs
├── common
│  ├── Cargo.toml
│  └── lib
│     └── common-module.rs
├── README.md
├── target
└── tests
```

### Example Cargo files

And here are the workspace cargo file. 
```yaml
[workspace]
members = [
    "common",
    "first_service",
    "second_service",
]

# Members inherit from the bellow sections
[workspace.package]
version = "1.7.37"      
authors = ["Your Team"]
description = "Your Workspace that does it all."

[workspace.dependencies]
anyhow = { version = "1.0.66", features = ["backtrace"] }
```

And here are the service or library cargo file. 
```yaml
[package]
name = "first_service"
version = { workspace = true }
edition = "2021"

[dependencies]
anyhow = { workspace = true }
dotenvy = "0.15.6"
```

**Comment by nicolaiunrein** [comment]
I had a look and I think it would be nice and reasonably simple to implement. Would you line to submit a PR? Otherwise I will implement it as soon as I find time.

**Comment by rguarnotta** [comment]
Same, I'll open a PR as soon as I find time for it. Thks.

**Comment by nicolaiunrein** [comment]
So I played around a little bit and I think I will change the syntax
I think I will deprecate the use of flags and instead provide subcommands which will match the path of the properties.
I would of course only hide the old syntax. It should still be available for people using `cargo-get` in scripts and CI.

```bash
# current syntax
$: cargo get version
$: cargo get --authors
$: cargo get --description

# will become:
$: cargo get package.version
$: cargo get package.authors
$: cargo get package.description

# and then it is easy to add workspace props as well:
$: cargo get workspace.package.version
$: cargo get workspace.package.authors
$: cargo get workspace.package.description
```
The new help page will then look like this (still incomplete):
```bash
$: cargo-get 
Nicolai Unrein <n.unrein@gmail.com>
Query package info from Cargo.toml in a script-friendly way.

USAGE:
    cargo-get [OPTIONS] [SUBCOMMAND]

FLAGS:
    -h, --help    Prints help information

OPTIONS:
        --root <PATH>                                  optional entry point
        --delimiter <Tab | CR | LF | CRLF | String>    specify delimiter for values

SUBCOMMANDS:
    package.version                  get package version
    package.authors                  get package authors
    package.categories               get package categories
    package.description              get package description
    package.edition                  get package edition
    package.homepage                 get package homepage
    package.keywords                 get package keywords
    package.license                  get package license
    package.version                  get package version
    workspace.members                get workspace members
    workspace.package.authors        get workspace template authors
    workspace.package.categories     get workspace template categories
    workspace.package.description    get workspace template description
    workspace.package.edition        get workspace template edition
    workspace.package.homepage       get workspace template homepage
    workspace.package.keywords       get workspace template keywords
    workspace.package.license        get workspace template license
    workspace.package.version        get workspace template version
    help                             Prints this message or the help of the given subcommand(s)

```
Please let me know what you think

**Comment by rguarnotta** [comment]
I think that's a good idea, I like it! 

Would `cargo get package.version`work for a package that is inheriting version from its parent workspace?

**Comment by nicolaiunrein** [comment]
no, `package.version` would always give you the actual version specified. For inheritance to work on workspace you need to specify `version.workspace = true` so the subcommand would be `cargo get package.version.workspace`. I could of course try to resolve the inheritance from the workspace template but I'm unsure whether this should be the default.

I think I would be better to be explicit here:
```
$: cargo get version.workspace
true

# and
$: cargo get version.workspace --resolve
2.3.4
```

**Comment by nicolaiunrein** [comment]
With `--resolve` set it would of course be possible to pass all the additional flags for version:
```
$: cargo get package.version.workspace --resolve --major --minor --delimiter="CRLF"
3
2
```

**Comment by nicolaiunrein** [comment]
I have to correct myself. Ignore the
```
$: cargo get package.version.workspace--resolve
```
I think it should in fact be:

```
$: cargo get package.version --resolve #or --inherit ??
```
and
```
$: cargo get package.version
```
should fail for inherited values to indicate that it is not specified on this crate.

**Comment by rguarnotta** [comment]
I reviewed your suggestion, I think it makes sense to implement it as your mentioned above: 

```

cargo get package.version  # to get package version, and returning an error if version is inherited
cargo get package.version --inherit # to get package version from workspace if inherited, and returning an error if version is not inherited
```

As for the inheritance flag, I have a preference for '--inherit' or `--parent`.

**Comment by nicolaiunrein** [comment]
@rguarnotta @meysam81 please have a look at #9 and let me know what you think!

**Comment by rguarnotta** [comment]
🙏

**Comment by rguarnotta** [comment]
This is great!
